### ISSUE TITLE
[Save] on Configuration said a-okay, but defs wasn't. 

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/pioreactorui#53]
pm2 output
```
0|ui       | 2021-05-19T19:37:44: 2021-05-19 19:37:41 [CLI] DEBUG Syncing configs on pioreactor1...
0|ui       | 2021-05-19T19:37:44: 2021-05-19 19:37:44 [CLI] ERROR Unable to connect to unit pioreactor1.
0|ui       | 2021-05-19T19:37:44: 2021-05-19 19:37:44 [CLI] DEBUG [Errno None] Unable to connect to port 22 on 192.168.1.9
0|ui       | 2021-05-19T19:37:44: Traceback (most recent call last):
0|ui       | 2021-05-19T19:37:44:   File "/home/pi/pioreactor/pioreactor/cli/pios.py", line 147, in _thread_function
0|ui       | 2021-05-19T19:37:44:     client.connect(unit, username="pi")
0|ui       | 2021-05-19T19:37:44:   File "/usr/local/lib/python3.7/dist-packages/paramiko/client.py", line 368, in connect
0|ui       | 2021-05-19T19:37:44:     raise NoValidConnectionsError(errors)
0|ui       | 2021-05-19T19:37:44: paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 192.168.1.9
0|ui       | 2021-05-19T19:37:44:

```

**Comment by CamDavidsonPilon** [comment]
Fixed this. All the `pios` commands weren't sending the correct linux error code, so nothing was reported.
